#:include front_panel_view.kv
#:include status_bar.kv


<DisplayBox>:
    name: 'Main Window'
    orientation: 'vertical'

    MDToolbar:
        title: 'VERBA SC156-R'
        md_bg_color: app.theme_cls.primary_color
        #left_action_items: [["menu", lambda x : x]]
        right_action_items: [["home", lambda x : app.set_screen('home_screen')], ["clock", lambda x : app.set_screen('process_screen')]]

    FrontPanelView:
        id: front_panel_view

    StatusBar:
        id: status_bar
